server:
  port:
    2468

spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/carmanagement?useUnicode=true&charactEncoding=utf-8&userSSL=true&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  typeAliasesPackage: "com.zhbit.pojo"
  mapper-locations: "classpath:mapper/*.xml"
  map-underscore-to-camel-case: false

jwt:
  secret_key: "ajbdfhjsbfjkj"
  exp_time: 1

mybatis-plus:
  configuration:
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: false

  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

  mapper-locations: "classpath:mapper/*.xml"
  typeAliasesPackage: "com.zhbit.pojo"